apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
      - name: ssh-container
        image: your-ssh-image:latest
        ports:
        - containerPort: 22
      - name: ngrok-container
        image: wernight/ngrok:latest
        command: ["ngrok", "tcp", "22"]
        ports:
        - containerPort: 4040
