

name: Connect to Linux server and configure ngrok


on: [push, workflow_dispatch]

jobs:
   build:
     runs-on: linux-latest
       
     steps:
      - name: Download
        run: god
      - name: Extract
        run: Expand-Archive ngrok.zip
      
      - name: Set ngrok authtoken
        run: .\ngrok\ngrok.exe authtoken 2audaLEp4eMmq4EcQhGe3RhMy6F_7EnuK4mQarfyeNDBK7v4c
        env:NGROK_AUTH_TOKEN: 2audaLEp4eMmq4EcQhGe3RhMy6F_7EnuK4mQarfyeNDBK7v4c

      - name: Open TCP tunnel with ngrok
        run: .\ngrok\ngrok.exe tcp 3389
