name: CI
 
on: [push, workflow_dispatch]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok

      - name: Connect to ngrok
      run: ./ngrok authtoken $Env:NGROK_AUTH_TOKEN && ./ngrok http 80
      
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
